CREATE DATABASE [AmazonCompra]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AmazonCompra', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AmazonCompra.mdf' 
, SIZE = 140288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'AmazonCompra_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AmazonCompra_log.ldf'
 , SIZE = 149696KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

USE AmazonCompra;
GO

CREATE TABLE Compra(
	ID INT IDENTITY(1,1) NOT NULL,
	PRIMARY KEY (ID)
)

CREATE TABLE CompraProduto(
	ID INT IDENTITY(1,1) NOT NULL, 
	CompraID INT NOT NULL FOREIGN KEY REFERENCES Compra(ID),
	ProdutoID INT NOT NULL,
	ValorProduto MONEY NOT NULL,
	PRIMARY KEY(ID)
)

CREATE TABLE Desejos(
	ID INT IDENTITY(1,1) NOT NULL,
	PRIMARY KEY(ID)
)

CREATE TABLE ItemDesejo(
	ID INT IDENTITY(1,1) NOT NULL,
	DesejoID INT NOT NULL FOREIGN KEY REFERENCES Desejos(ID),
	ProdutoID INT NOT NULL,
	PRIMARY KEY(ID)
)
