version: "3.1"
networks:
  support:
      driver: bridge
services:
    app:
      user: root
      container_name: apppurchase
      env_file: .env
      build: 
        context: .
        dockerfile: dotnet.dockerfile
      ports: 
        - ${APP_PORT}:80
      depends_on:
        - database
      networks:
        - support
      environment:
        - WAIT_HOSTS=mysql:3306
        - WAIT_HOSTS_TIMEOUT=300
        - WAIT_SLEEP_INTERVAL=30
        - WAIT_HOST_CONNECT_TIMEOUT=30
    database:
      container_name: databasepurchase
      image: mysql:8.0
      ports:
        - ${DATABASE_PORT}:3306
      env_file: .env
      restart: always
      volumes:
        - volume-data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: ${DBPassword}
        MYSQL_DATABASE: ${DBName}
      networks:
        - support
      healthcheck:
        test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
        timeout: 20s
        retries: 10
volumes:
   volume-data: